name: Sync Raw JSON Data

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch pure JSON
        run: |
          # Voeg deze header toe om HTML te omzeilen
          curl -s -H "Accept: application/json" "https://script.google.com/macros/s/AKfycbw8MHQH8V75bxn68rPSoiY5dLti6tVBFmACPWyDMprcKikNkDcCJJxAld-16-FHITYi/exec" > data.json
          
          # Valideer of het echte JSON is
          jq empty data.json || (echo "Geen geldige JSON!" && exit 1)

      - name: Push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Update: $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
