name: Sync Data Every 5 Minutes

on:
  schedule:
    - cron: '*/1 * * * *'  # Elke 5 minuten
  workflow_dispatch:       # Handmatig triggeren mogelijk

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch data from Google Script
        run: |
          curl "https://script.google.com/macros/s/AKfycbw8MHQH8V75bxn68rPSoiY5dLti6tVBFmACPWyDMprcKikNkDcCJJxAld-16-FHITYi/exec" > data.json
      
      - name: Commit & Push
        run: |
          git config --global user.name "Automated Sync"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Auto-update data" || echo "Geen wijzigingen"
          git push
