name: Sync Data Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # STAP 1: Checkout de repository eerst!
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Zorgt dat alle Git history wordt opgehaald

      # STAP 2: Haal de data op
      - name: Fetch data
        run: |
          curl -s "https://script.google.com/macros/s/AKfycbw8MHQH8V75bxn68rPSoiY5dLti6tVBFmACPWyDMprcKikNkDcCJJxAld-16-FHITYi/exec" > data.json
          echo "Data van $(date)" >> log.txt  # Debug

      # STAP 3: Push wijzigingen
      - name: Commit & Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push
